source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-activerecord'
gem 'rake'
gem 'pry'
gem 'sqlite3', '~>1.3.6'
gem 'activerecord'
gem 'shotgun'
gem 'bcrypt'
gem 'require_all'
gem 'sinatra-flash'